# ===================================================================
# CONFIGURAÇÃO GERAL DO EXPERIMENTO
# ===================================================================

# -------------------------------------------------------------------
# Seção de Dados: Define o dataset, a semente para reprodutibilidade
# e a estratégia de validação cruzada.
# -------------------------------------------------------------------
dataset:
  path: "data/RealWaste"
  random_seed: 42

cross_validation:
  n_splits: 10

# -------------------------------------------------------------------
# Seção do Modelo: Parâmetros que definem a arquitetura do modelo.
# -------------------------------------------------------------------
model:
  image_size: 128

# -------------------------------------------------------------------
# Seção de Treinamento: Todos os hiperparâmetros que controlam
# o processo de treinamento.
# -------------------------------------------------------------------
training:
  batch_size: 16
  num_workers: 0
  epochs: 5000
  learning_rate: 0.0001
  optimizer: 'Adam'     # Usado para referência, o código usa Adam diretamente
  weight_decay: 5e-4
  early_stopping_patience: 15
  scheduler_patience: 5